# The Site Configuration
#
# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage > http://www.lingoes.net/en/translator/langcode.htm
# If it has the same name as one of the files in folder `_data/locales`,
# the layout language will also be changed, otherwise, the layout language will use the lang: en
lang: en

# Change to your timezone > https://zones.arilyn.cc
timezone: Africa/Nairobi

# jekyll-seo-tag settings > https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# â†“ --------------------------
title: Kitine Dancan OKINYI
tagline: "Cybersecurity Professional & Enthusiast"

url: "https://Jlaura08.github.io"
baseurl: ""

# ... [other settings] ...

github:
  username: Jlaura08
